version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
  db:
    image: mongo:4.4
    ports:
      - "27017:27017"
